### PR TITLE
chore: rename to odyssey and set EXP1 env vars

### PR DESCRIPTION
**Pull request by klkvr**
for now just hardcoded the first address from dev mnemonic and contract which it can deploy with nonce 0.

Also disables sequencer forwarding configuration and enables discv4 for EL

### CODE REVIEW

**Review by jenpaff — APPROVED** [review]
lgtm

**Review by onbjerg — COMMENTED** [review]
I think we should use something that isn't the first dev address, given this is likely the one people will use to send transactions with.

**Comment by klkvr** [comment]
> I think we should use something that isn't the first dev address, given this is likely the one people will use to send transactions with.

changed to use 5'th address (0x9965507D1a55bcC2695C58ba16FB37d819B0A4dc, private key 0x8b3a350cf5c34c9194ca85829a2df0ec3153be0318b5e2d3348e872092edffba)

we could just add a random private key here but then we'd need to add logic for prefunding it, I think it should be fine for now? especially given that package will mostly be used by us for automated testing for now

**Review by onbjerg — APPROVED** [review]

**Comment by jenpaff** [comment]
@klkvr @onbjerg is this one good to merge?

**Comment by onbjerg** [comment]
yes!

**Pull request merged**
